<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * DestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
	/** récuperer les photos dans l'ordre de publication **/
	public function findPhotoByUser($page, $nbPerPage, $userid)
    {
        $query = $this->createQueryBuilder('p')
            ->join('p.user', 'u')
            ->where('u.id = :user')
            ->setParameter('user', $userid)
            ->orderBy('p.position', 'desc')
            ->getQuery()
        ;

    $query->setFirstResult(($page-1) * $nbPerPage)
          ->setMaxResults($nbPerPage)
    ;

        return new Paginator($query, true);
        // return $qb->getQuery()->getResult();
    }

    public function findPhotoPubliee($userid)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('COUNT(p.position)') 
            ->from('AppBundle:Photo', 'p')
            ->join('p.user', 'u')
            ->where('u.id = :user')
            ->andwhere('p.position != 0')
            ->setParameter('user', $userid)
            ->orderBy('p.position','asc')
        ;

        return $qb->getQuery()->getSingleResult();
    }

    public function findModifPosition($position, $idUser)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('p.id, p.position')
                ->from('AppBundle:Photo', 'p')
                ->join('p.user', 'u')
                ->where('u.id = :user')
                ->andwhere('p.position >= :position')
                ->setParameter('user', $idUser)
                ->setParameter('position', $position)
                ->orderBy('p.position')
        ;

        return $qb->getQuery()->getResult();
    }

    public function findModifDoublePosition($positionhaute, $positionbasse, $idUser)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('p.id, p.position')
                ->from('AppBundle:Photo', 'p')
                ->join('p.user', 'u')
                ->where('u.id = :user')
                ->andwhere('p.position > :positionbasse')
                ->andwhere('p.position <= :positionhaute')
                ->setParameter('user', $idUser)
                ->setParameter('positionbasse', $positionbasse)
                ->setParameter('positionhaute', $positionhaute)
                ->orderBy('p.position')
        ;

        return $qb->getQuery()->getResult();
    }

    public function findUserAvecPhotoPubliee()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('DISTINCT u.id')
                ->from('AppBundle:Photo', 'p')
                ->join('p.user', 'u')
                ->where('p.user = u.id')
                ->where('p.position > 0')
                ->orderBy('p.position')
        ;

        return $qb->getQuery()->getResult();
    }

    public function findPhotoPublieeDuRand($user)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('p')
                ->from('AppBundle:Photo', 'p')
                ->join('p.user', 'u')
                ->andwhere('u.id = :user')
                ->andwhere('p.position > 0')
                ->setParameter('user', $user)
                ->orderBy('p.position')
        ;

        return $qb->getQuery()->getResult();
    }

}