<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * DestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

	public function randUser()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('u') 
            ->from('AppBundle:User', 'u')
            ->join('AppBundle:Photo', 'p')
            ->where('p.user = u.id')
            // ->andwhere('COUNT(p) >= 1')
            // ->orderBy('p.position','asc')
        ;

        return $qb->getQuery()->getResult();
    }
}